### ISSUE TITLE
How to create SELECT COUNT(DISTINCT ...) type of expression?

### ISSUE THREAD

**Issue by valeeum** [exjs/xql#3]
How can i create an expression that performs a distinct count?

**Comment by kobalicek** [comment]
Hello, it's quite some time I used this library, but I just tried and this should work for you:

```js
return SELECT( COUNT("x").DISTINCT() ).FROM("sometable");
```

When you create a `COUNT()` node, you can use its member function `DISTINCT()` to flag it as distinct.

Hope that helps

**Comment by valeeum** [comment]
That worked, thanks so much!
