### ISSUE TITLE
'CASE' Example Not Working

### ISSUE THREAD

**Issue by valeeum** [exjs/xql#4]
I get the following error:

`TypeError: Object(...) is not a function`

when the following code is run:

```
    const query = SELECT([
      'id',
      CASE()
        .WHEN(EQ(COL('a'), 1), 'some thing')
        .WHEN(EQ(COL('a'), 2), 'another thing')
        .ELSE('nothing'),
    ]).FROM('tasks');
```

This snippet was pulled directly from the online fiddler for xql: https://kobalicek.com/fiddle-xql.html
 
Any idea why that is the case?

**Comment by kobalicek** [comment]
I checked it out, if you installed from npm there is an old version, will publish the latest one.

**Comment by kobalicek** [comment]
BTW I updated the npm package, still having the issue?

**Comment by valeeum** [comment]
no that did it!
