### ISSUE TITLE
Provide a get API on the dialect object to retrieve registered dialects so they can be extended

### ISSUE THREAD

**Issue by charlesprakash** [exjs/xql#7]
It would be great to be able to retrieve registered dialects in order to extend them. For e.g.

```
let MySqlContext = xql.dialect.get("mysql");
class CustomMySqlContext extends MySqlContext {
 ...
}

```

**Comment by kobalicek** [comment]
Commit https://github.com/exjs/xql/commit/454f7bd3b3731eb752422a44e85071e925a6aa99 adds the possiblity to introspect SQL dialects through `xql.dialect.registry` object. Thanks for this suggestion!
